-- ----------------------------------------------------------
--    CUSTOMER BEHAVIOUR ANALYSIS 
-- ----------------------------------------------------------

CREATE DATABASE IF NOT EXISTS Customer_behaviour;
USE Customer_behaviour;

-- ----------------------------------------------------------
-- Preview Data
-- ----------------------------------------------------------
SELECT * FROM customer LIMIT 2;

-- Total number of rows
SELECT COUNT(*) FROM customer;

-- ----------------------------------------------------------
-- Q1: Total revenue generated by male vs female customers
-- ----------------------------------------------------------
SELECT 
    gender, 
    SUM(purchase_amount) AS Revenue
FROM customer
GROUP BY gender;

-- ----------------------------------------------------------
-- Q2: Customers who used a discount AND spent more than the AVG purchase amount
-- ----------------------------------------------------------
SELECT 
    customer_id, 
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- ----------------------------------------------------------
-- Q3: Top 5 products with the highest average review rating
-- ----------------------------------------------------------
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS Average_Product_Rating
FROM customer
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;

-- ----------------------------------------------------------
-- Q4: Compare average purchase amount between Standard vs Express shipping
-- ----------------------------------------------------------
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS Avg_Purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- ----------------------------------------------------------
-- Q5: Do subscribed customers spend more?
--      (Avg Spend + Total Revenue Comparison)
-- ----------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, average_spend DESC;

-- ----------------------------------------------------------
-- Q6: Top 5 products with highest percentage of discounted purchases
-- ----------------------------------------------------------
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE 
                        WHEN discount_applied = 'Yes' THEN 1 
                        ELSE 0 
                    END) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- ----------------------------------------------------------
-- Q7: Customer Segmentation (New, Returning, Loyal)
-- ----------------------------------------------------------
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- ----------------------------------------------------------
-- Q8: Top 3 most purchased products within each category
-- ----------------------------------------------------------
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- ----------------------------------------------------------
-- Q9: Are repeat buyers (>5 previous purchases) more likely to subscribe?
-- ----------------------------------------------------------
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- ----------------------------------------------------------
-- Q10: Revenue contribution by each age group
-- ----------------------------------------------------------
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
